default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: rails_blog_alpha_dev
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  database: rails_blog_alpha_test
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  database: rails_blog_alpha_prod
  pool: 5
  timeout: 5000
